services:
  - type: web
    name: ukrace2space-app
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    region: frankfurt
    autoDeploy: true
    instanceCount: 1
    envVars:
      - key: ENVIRONMENT
        value: "production"
      - key: DEBUG
        value: "0"
    healthCheckPath: /query
    healthCheckIntervalSeconds: 10
